const awStructures = {
  AW00: [
    { name: "AWB-REC-0-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "TRAXON-BRANCH-ID", lenght: 20, start: 5, end: 24 },
    { name: "AWB-MESSAGE-ID", lenght: 20, start: 25, end: 44 },
    { name: "HAWB-RUNNING-NUMBER", lenght: 3, start: 45, end: 47 },
    { name: "HAWB-MESSAGE-ID", lenght: 20, start: 48, end: 67 },
    { name: "ETD-DATE", lenght: 8, start: 68, end: 75 },
    { name: "ETD-TIME", lenght: 4, start: 76, end: 79 },
    { name: "TIME-ZONE", lenght: 3, start: 80, end: 82 },
    { name: "ETA-DATE", lenght: 8, start: 83, end: 90 },
    { name: "ETA-TIME", lenght: 4, start: 91, end: 94 },
    { name: "CR-DATE", lenght: 8, start: 95, end: 102 },
    { name: "CR-TIME", lenght: 6, start: 103, end: 108 },
    { name: "MAWB-USING-CODE", lenght: 1, start: 109, end: 109 },
    { name: "HAWB-USING-CODE", lenght: 1, start: 110, end: 110 },
    { name: "NATURE-OF-GOODS", lenght: 3, start: 111, end: 113 },
    { name: "CIS-REFERENCE-NUMBER", lenght: 20, start: 114, end: 133 },
    { name: "FINAL-DESTINATION-BRANCH", lenght: 10, start: 134, end: 143 },
    { name: "STATUS", lenght: 10, start: 144, end: 153 },
    { name: "S-PROJECT-ID", lenght: 10, start: 154, end: 163 },
    { name: "SERVICE-LEVEL-ID", lenght: 2, start: 164, end: 165 },
    { name: "SERVICE-LEVEL-TYPE", lenght: 2, start: 166, end: 167 },
    { name: "SERVICE-LEVEL-TRANSITTIME", lenght: 3, start: 168, end: 170 },
  ],
  AW10: [
    { name: "AWB-REC-1-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "BGM-DOCUMENT-CODE", lenght: 3, start: 5, end: 7 },
    { name: "BGM-DOCUMENT-NO.", lenght: 17, start: 8, end: 24 },
    { name: "BGM-MAWB-NO.", lenght: 17, start: 25, end: 41 },
    { name: "BGM-MESSAGE-FUNCTION", lenght: 3, start: 41, end: 44 },
    { name: "DTM-DOCUMENT-DATE", lenght: 8, start: 45, end: 52 },
    { name: "DTM-DATE-ID", lenght: 3, start: 53, end: 55 },
    { name: "CUX-AWB-DECLARED-CURRENCY-CODE", lenght: 3, start: 56, end: 58 },
    { name: "CUX-CC-DEST-CURRENCY-CODE", lenght: 3, start: 59, end: 61 },
    { name: "CUX-EXCHANGE-RATE", lenght: 12, start: 62, end: 73 },
    {
      name: "CUX-AWB-FREIGHT-OTHER-CHARGES-CURRENCY-CODE",
      lenght: 3,
      start: 74,
      end: 76,
    },
  ],
  AW20: [
    { name: "AWB-REC-2-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "MOA-DV-CARRIAGE", lenght: 18, start: 5, end: 22 },
    { name: "MOA-DV-CUSTOMS", lenght: 18, start: 23, end: 40 },
    { name: "MOA-DV-INSURANCE", lenght: 18, start: 41, end: 58 },
    { name: "MOA-CC-DC-CHARGES", lenght: 18, start: 59, end: 76 },
    { name: "MOA-CC-DC-OTHER-CHARGES", lenght: 18, start: 77, end: 94 },
    { name: "MOA-CC-DC-CHARGES-TOTAL", lenght: 18, start: 95, end: 112 },
  ],
  AW25: [
    { name: "AWB-REC-3-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "MOA-PP-WEIGHT-CHARGES", lenght: 18, start: 5, end: 22 },
    { name: "MOA-PP-VALUATION-CHARGES", lenght: 18, start: 23, end: 40 },
    { name: "MOA-PP-TAX-CHARGES", lenght: 18, start: 41, end: 58 },
    { name: "MOA-PP-OTHER-CHARGES-DUE-AGENT", lenght: 18, start: 59, end: 76 },
    {
      name: "MOA-PP-OTHER-CHARGES-DUE-CARRIER",
      lenght: 18,
      start: 77,
      end: 94,
    },
    { name: "MOA-PP-CHARGES-TOTAL", lenght: 18, start: 95, end: 112 },
    { name: "MOA-CC-WEIGHT-CHARGES", lenght: 18, start: 113, end: 130 },
    { name: "MOA-CC-VALUATION-CHARGES", lenght: 18, start: 131, end: 148 },
    { name: "MOA-CC-TAX-CHARGES", lenght: 18, start: 149, end: 166 },
    {
      name: "MOA-CC-OTHER-CHARGES-DUE-AGENT",
      lenght: 18,
      start: 167,
      end: 184,
    },
    {
      name: "MOA-CC-OTHER-CHARGES-DUE-CARRIER",
      lenght: 18,
      start: 185,
      end: 202,
    },
    { name: "MOA-CC-CHARGES-TOTAL", lenght: 18, start: 203, end: 220 },
  ],
  AW30: [
    { name: "AWB-REC-4-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "FTX-HI-IDENTIFIER", lenght: 3, start: 5, end: 7 },
    { name: "FTX-HI-TEXT-1", lenght: 70, start: 8, end: 77 },
    { name: "FTX-HI-TEXT-2", lenght: 4, start: 78, end: 81 },
  ],
  AW35: [
    { name: "AWB-REC-5-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "FTX-AI-ID", lenght: 3, start: 5, end: 7 },
    { name: "FTX-AI-TEXT", lenght: 70, start: 8, end: 77 },
  ],
  AW40: [
    { name: "AWB-REC-6-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "LOC-PLACE-OF-DEPARTURE", lenght: 3, start: 5, end: 7 },
    { name: "LOC-PLACE-OF-DESTINATION", lenght: 3, start: 8, end: 10 },
    { name: "TDT-R-TRANSPORT STAGE-ID", lenght: 3, start: 11, end: 13 },
    { name: "TDT-FB-CARRIER-CODE", lenght: 2, start: 14, end: 15 },
    { name: "TDT-FB-FLIGHT-NUMBER", lenght: 4, start: 16, end: 19 },
    { name: "TDT-FB-DAY", lenght: 2, start: 20, end: 21 },
    { name: "TDT-R-DESTINATION", lenght: 3, start: 22, end: 24 },
    { name: "TDT-R-TRANSPORT STAGE-ID", lenght: 3, start: 11, end: 13 },
    { name: "TDT-FB-CARRIER-CODE", lenght: 2, start: 14, end: 15 },
    { name: "TDT-FB-FLIGHT-NUMBER", lenght: 4, start: 16, end: 19 },
    { name: "TDT-FB-DAY", lenght: 2, start: 20, end: 21 },
    { name: "TDT-R-DESTINATION", lenght: 3, start: 22, end: 24 },
    { name: "TDT-R-TRANSPORT STAGE-ID", lenght: 3, start: 11, end: 13 },
    { name: "TDT-FB-CARRIER-CODE", lenght: 2, start: 14, end: 15 },
    { name: "TDT-FB-FLIGHT-NUMBER", lenght: 4, start: 16, end: 19 },
    { name: "TDT-FB-DAY", lenght: 2, start: 20, end: 21 },
    { name: "TDT-R-DESTINATION", lenght: 3, start: 22, end: 24 },
    { name: "CPI-TRANSPORT-CHARGES", lenght: 3, start: 53, end: 55 },
    { name: "CPI-WEIGHT-VALUATION-CHARGES", lenght: 3, start: 56, end: 58 },
    { name: "CPI-OTHER-CHARGES", lenght: 3, start: 59, end: 61 },
  ],
  AW41: [
    { name: "AWB-REC-6-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "LOC-PLACE-OF-DEPARTURE", lenght: 3, start: 5, end: 7 },
    { name: "LOC-PLACE-OF-DESTINATION", lenght: 3, start: 8, end: 10 },
    { name: "TDT-R-TRANSPORT STAGE-ID-1", lenght: 3, start: 11, end: 13 },
    { name: "TDT-R-TRANSPORT STAGE-ID-2", lenght: 3, start: 26, end: 28 },
    { name: "TDT-R-TRANSPORT STAGE-ID-3", lenght: 3, start: 41, end: 43 },
    { name: "TDT-FB-CARRIER-CODE-1", lenght: 2, start: 14, end: 15 },
    { name: "TDT-FB-CARRIER-CODE-2", lenght: 2, start: 29, end: 30 },
    { name: "TDT-FB-CARRIER-CODE-3", lenght: 2, start: 44, end: 45 },
    { name: "TDT-FB-FLIGHT-NUMBER-1", lenght: 5, start: 16, end: 20 },
    { name: "TDT-FB-FLIGHT-NUMBER-2", lenght: 5, start: 31, end: 35 },
    { name: "TDT-FB-FLIGHT-NUMBER-3", lenght: 5, start: 46, end: 50 },
    { name: "TDT-FB-DAY-1", lenght: 2, start: 21, end: 22 },
    { name: "TDT-FB-DAY-2", lenght: 2, start: 36, end: 37 },
    { name: "TDT-FB-DAY-3", lenght: 2, start: 51, end: 52 },
    { name: "TDT-R-DESTINATION-1", lenght: 3, start: 23, end: 25 },
    { name: "TDT-R-DESTINATION-2", lenght: 3, start: 38, end: 40 },
    { name: "TDT-R-DESTINATION-3", lenght: 3, start: 53, end: 55 },
    { name: "CPI-TRANSPORT-CHARGES", lenght: 3, start: 56, end: 58 },
    { name: "CPI-WEIGHT-VALUATION-CHARGES", lenght: 3, start: 59, end: 61 },
    { name: "CPI-OTHER-CHARGES", lenght: 3, start: 62, end: 64 },
  ],
  AW45: [
    { name: "AWB-REC-7-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "TCC-COC-ID", lenght: 3, start: 5, end: 7 },
    { name: "TCC-COC-TEXT", lenght: 35, start: 8, end: 42 },
    { name: "TCC-COC-PREPAID-COLLECT", lenght: 3, start: 43, end: 45 },
    { name: "TCC-COC-DUE-AGENT-CARRIER", lenght: 3, start: 46, end: 48 },
    { name: "TCC-COC-AMOUNT", lenght: 18, start: 49, end: 66 },
  ],
  AW50: [
    { name: "AWB-REC-8-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "NAD-SCN-ADDRESS-QUALIFIER", lenght: 3, start: 5, end: 7 },
    { name: "NAD-SCN-ADDRESS-ID", lenght: 17, start: 8, end: 24 },
    { name: "NAD-SCN-CODE-LIST", lenght: 3, start: 25, end: 27 },
    { name: "NAD-SCN-ADDRESS-STRUCTURE", lenght: 1, start: 28, end: 28 },
    { name: "NAD-SCN-NAME-AND-ADDRESS-LINE-1", lenght: 35, start: 29, end: 63 },
    { name: "NAD-SCN-NAME-AND-ADDRESS-LINE-2", lenght: 35, start: 64, end: 98 },
    {
      name: "NAD-SCN-NAME-AND-ADDRESS-LINE-3",
      lenght: 35,
      start: 99,
      end: 133,
    },
    {
      name: "NAD-SCN-NAME-AND-ADDRESS-LINE-4",
      lenght: 35,
      start: 134,
      end: 168,
    },
    {
      name: "NAD-SCN-NAME-AND-ADDRESS-LINE-5",
      lenght: 35,
      start: 169,
      end: 203,
    },
    { name: "NAD-SCN-REFERENCE-NUMBER", lenght: 35, start: 204, end: 238 },
    { name: "NAD-SCN-VAT-NUMBER", lenght: 35, start: 239, end: 273 },
    {
      name: "NAD-SCN-ADDRESS-IDENTIFACTION-NUMBER",
      lenght: 35,
      start: 274,
      end: 308,
    },
    { name: "NAD-SCN-CIS-REFERENCE", lenght: 35, start: 309, end: 343 },
  ],
  AW51: [
    { name: "AWB-REC-81-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "NAD-SCN1-ADDRESS-QUALIFIER", lenght: 3, start: 5, end: 7 },
    { name: "NAD-SCN1-ADDRESS-ID", lenght: 17, start: 8, end: 24 },
    { name: "NAD-SCN1-CODE-LIST", lenght: 3, start: 25, end: 27 },
    { name: "NAD-SCN1-ADDRESS-STRUCTURE", lenght: 1, start: 28, end: 28 },
    { name: "NAD-SCN1-NAME-1", lenght: 35, start: 29, end: 63 },
    { name: "NAD-SCN1-NAME-2", lenght: 35, start: 64, end: 98 },
    { name: "NAD-SCN1-STREET-AND-NUMBER-1", lenght: 35, start: 99, end: 133 },
    { name: "NAD-SCN1-STREET-AND-NUMBER-2", lenght: 35, start: 134, end: 168 },
    { name: "NAD-SCN1-CITY-NAME", lenght: 35, start: 169, end: 203 },
    { name: "NAD-SCN1-STATE", lenght: 9, start: 204, end: 212 },
    { name: "NAD-SCN1-POST-CODE", lenght: 9, start: 213, end: 221 },
    { name: "NAD-SCN1-COUNTRY-CODE", lenght: 3, start: 222, end: 224 },
    { name: "NAD-SCN1-REFERENCE-NUMBER", lenght: 35, start: 225, end: 259 },
    { name: "NAD-SCN1-VAT-NUMBER", lenght: 35, start: 260, end: 294 },
    {
      name: "NAD-SCN1-ADDRESS-IDENTIFACTION-NUMBER",
      lenght: 35,
      start: 295,
      end: 329,
    },
    { name: "NAD-SCN-CIS-REFERENCE", lenght: 35, start: 330, end: 364 },
  ],
  AW55: [
    { name: "AWB-REC-9-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "NAD-COM-ADDRESS-ID", lenght: 3, start: 5, end: 7 },
    { name: "NAD-COM-CONTACT-FUNCTION", lenght: 3, start: 8, end: 10 },
    { name: "NAD-COM-CONTACT-DEPARTMENT", lenght: 17, start: 11, end: 27 },
    { name: "NAD-COM-CONTACT-EMPLOYEE", lenght: 35, start: 28, end: 62 },
    { name: "NAD-COM-COMMUNICATION-ID", lenght: 3, start: 62, end: 65 },
    { name: "NAD-COM-COMMUNICATION-NUMBER", lenght: 25, start: 66, end: 90 },
    { name: "NAD-COM-CCAM-ID-QUALIFIER", lenght: 28, start: 91, end: 118 },
    { name: "NAD-COM-CCAM-ID-NUMBER", lenght: 28, start: 119, end: 146 },
  ],
  AW60: [
    { name: "AWB-REC-10-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "NAD-AG-NAME", lenght: 35, start: 5, end: 39 },
    { name: "NAD-AG-CITY-NAME", lenght: 35, start: 40, end: 74 },
    { name: "NAD-AG-STT-NUMBER", lenght: 35, start: 75, end: 109 },
    {
      name: "NAD-AG-IATA-CARGO-AGENT-NUMERIC-CODE",
      lenght: 35,
      start: 110,
      end: 144,
    },
    {
      name: "NAD-AG-IATA-CARGO-AGENT-CASS-ADDRESS",
      lenght: 35,
      start: 145,
      end: 179,
    },
    {
      name: "NAD-AG-IATA-CARGO-AGENT-ACCOUNTING-NO",
      lenght: 35,
      start: 180,
      end: 214,
    },
    { name: "NAD-SC-SIGNATURE", lenght: 35, start: 215, end: 249 },
    { name: "NAD-CE-SIGNATURE", lenght: 35, start: 250, end: 284 },
    { name: "NAD-CE-CITY NAME", lenght: 35, start: 285, end: 319 },
  ],
  AW70: [
    { name: "AWB-REC-11-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "GID-ITEM-NUMBER", lenght: 2, start: 5, end: 6 },
    { name: "GID-RATE-COMBINATION-POINT", lenght: 3, start: 7, end: 9 },
    { name: "GID-NUMBER-OF-PIECES", lenght: 8, start: 10, end: 17 },
    { name: "GID-GOODS-DATA-ID", lenght: 3, start: 18, end: 20 },
    { name: "GID-GOODS-TEXT-1", lenght: 70, start: 21, end: 90 },
    { name: "GID-GOODS-TEXT-2", lenght: 7, start: 91, end: 97 },
    { name: "GID-TCC-CHARGE-GROSS-WEIGHT", lenght: 15, start: 98, end: 112 },
    { name: "GID-TCC-GROSS-WEIGHT-CODE", lenght: 3, start: 113, end: 115 },
    { name: "GID-TCC-CHARGE-WEIGHT", lenght: 7, start: 116, end: 130 },
    { name: "GID-TCC-CHARGE-WEIGHT-CODE", lenght: 3, start: 131, end: 133 },
    { name: "GID-TCC-FREIGHT-RATE", lenght: 15, start: 134, end: 148 },
    { name: "GID-TCC-RATE-CLASS-CODE", lenght: 6, start: 149, end: 154 },
    { name: "GID-TCC-ULD-RATE-TYPE-CODE", lenght: 3, start: 155, end: 157 },
    { name: "GID-TCC-SUPPL-RATE-BASIS-ID", lenght: 6, start: 158, end: 163 },
    { name: "GID-TCC-CHARGE-AMOUNT", lenght: 18, start: 164, end: 181 },
    { name: "GID-TCC-COMMODITY-ITEM-NUMBER", lenght: 16, start: 182, end: 197 },
    { name: "GID-TCC-CATEGORY-OF-GOODS", lenght: 2, start: 198, end: 199 },
    { name: "GID-TCC-CLASS-RATE-PERCENTAGE", lenght: 8, start: 200, end: 207 },
    { name: "GID-TCC-PERCENTAGE-BASIC-CODE", lenght: 3, start: 208, end: 210 },
  ],
  AW75: [
    { name: "AWB-REC-12-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "GID-MEA-APPLICATION-QUALIFIER", lenght: 3, start: 5, end: 7 },
    { name: "GID-MEA-UNIT-QUALIFIER", lenght: 3, start: 8, end: 10 },
    { name: "GID-MEA-VALUE", lenght: 18, start: 11, end: 28 },
  ],
  AW76: [
    { name: "AWB-REC-13-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "GID-DIM-MEASURE-UNIT", lenght: 3, start: 5, end: 7 },
    { name: "GID-DIM-lenght:", lenght: 7, start: 8, end: 14 },
    { name: "GID-DIM-WIDTH", lenght: 7, start: 15, end: 21 },
    { name: "GID-DIM-HEIGHT", lenght: 7, start: 22, end: 28 },
    { name: "GID-EQN-NUMBER-OF-UNITS", lenght: 8, start: 29, end: 36 },
  ],
  AW95: [
    { name: "AWB-REC-14-QUALIFIER", lenght: 4, start: 1, end: 4 },
    { name: "CNT-TOTAL-NUMBER-OF-PIECES", lenght: 15, start: 5, end: 19 },
    { name: "CNT-TOTAL-GROSS-WEIGHT", lenght: 15, start: 20, end: 34 },
    { name: "CNT-TOTAL-GROSS-WEIGHT-CODE", lenght: 3, start: 35, end: 37 },
    { name: "CNT-TOTAL-CHARGE-WEIGHT", lenght: 15, start: 38, end: 52 },
    { name: "CNT-TOTAL-CHARGE-WEIGHT-CODE", lenght: 3, start: 53, end: 55 },
    { name: "CNT-TOTAL-VOLUME-WEIGHT", lenght: 15, start: 56, end: 70 },
    { name: "CNT-TOTAL-VOLUME-WEIGHT-CODE", lenght: 3, start: 71, end: 73 },
  ],
};
